### ISSUE TITLE
ABRoot removes groups added by packages added to host system

### ISSUE THREAD

**Issue by artyom-smushkov** [Vanilla-OS/ABRoot#344]
I tried to add docker to VanillaOS Orchid installed in GNOME Boxes VM, I tried both building my custom image with docker
```
...
  - name: important-packages # Sample module using the built-in Apt module to install packages
    type: apt
    source:
      packages:
      - docker.io
...
```
and  `abroot pkg add docker.io`/`abroot pkg apply` , package is installed but `docker` group is not in `/etc/group` and docker socket cannot be started because of it. I also tried it with `sddm` package and `sddm` group is also not there. When installing them inside of `vso-os-shell` with `sudo apt install docker.io sddm` both groups are there along with groups added by `sddm` dependencies, so I guess ABRoot removes them when it is doing its special merge of `group` file.

**Comment by artyom-smushkov** [comment]
Some additional info. Custom vib recipe section:

``` yaml
  # Put your custom actions behind this comment

  - name: mullvad
    type: shell
    commands:
      - curl -fsSLo /usr/share/keyrings/mullvad-keyring.asc https://repository.mullvad.net/deb/mullvad-keyring.asc
      - echo "deb [signed-by=/usr/share/keyrings/mullvad-keyring.asc arch=$( dpkg --print-architecture )] https://repository.mullvad.net/deb/stable sid main" | tee /etc/apt/sources.list.d/mullvad.list
      - apt-get update

  - name: packages
    type: apt
    source:
      packages:
        - mullvad-vpn
        - docker.io

  # Put your custom actions before this comment
```

After `abroot upgrade` FSGuard integrity check fails, after booting into broken system here is what I see in host shell:

``` sh
$ ls /opt
$ ls /.system/opt/
'Mullvad VPN'
$ cat /etc/group | grep docker
$ cat /.system/etc/group | grep docker

```
